#!/bin/bash
if [ -z "$1" ]; then
  echo "Usage: $0 <artifactId>"
  exit 1
fi
if [ -z "$2" ]; then
    mvn archetype:generate \
    -DgroupId=com.gemini \
    -DartifactId=$1 \
    -DinteractiveMode=false
else
    mvn archetype:generate \
    -DgroupId=com.gemini.$1 \
    -DartifactId=$2 \
    -DinteractiveMode=false
fi
